- name: Create a new node hierarchy
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml

  tasks:

    - name: Create a Hierarchy node
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: configuration_node
        data: { "node-path": "/md/SJC"}
        verify_cert: false
