---
-  hosts: switch1

   tasks:
     - name: VLAN configuration
       arubaoscx_vlan:
         vlan_id: "{{ item.vlan_id }}"
         name: "{{ item.name }}"
         description: "{{ item.description }}"
         state: "{{ item.state }}"
       with_items:
         - { vlan_id: 2, name: VLAN2, description: testvlan2, state: 'present' }
         - { vlan_id: 3, name: VLAN3, description: testvlan3, state: 'present' }
         - { vlan_id: 4, name: VLAN4, description: testvlan4, state: 'present' }

     - name: Layer2 Interface configuration
       arubaoscx_l2_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         vlan_mode: "{{ item.vlan_mode }}"
         vlan_id: "{{ item.vlan_id }}"
         vlan_trunk_native_id: "{{ item.vlan_trunk_native_id }}"
         vlan_trunk_native_tag: "{{ item.vlan_trunk_native_tag }}"
         qos_rate: "{{ item.qos_rate }}"
         qos_schedule_profile: "{{ item.qos_schedule_profile }}"
         aclv6_in: "{{ item.aclv6_in }}"
         aclv4_in: "{{ item.aclv4_in }}"
         aclmac_in: "{{ item.aclmac_in }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/2, admin_state: up, description: 'TestInterface1/1/2', vlan_mode: trunk, vlan_id: [1,2], vlan_trunk_native_id: 2, vlan_trunk_native_tag: true, qos_rate: {'unknown-unicast': 100pps, 'broadcast': 200pps, 'multicast': 200pps}, qos_schedule_profile: dwrr, aclv4_in: testv4, aclv6_in: testv6, aclmac_in: testmac, state: 'present' }
         - { interface: 1/1/3, admin_state: up, description: 'TestInterface1/1/3', vlan_mode: trunk, vlan_id: [3,4], vlan_trunk_native_id: 4, vlan_trunk_native_tag: false, qos_rate: {'unknown-unicast': 100pps, 'broadcast': 100pps, 'multicast': 300pps}, qos_schedule_profile: dwrr, aclv4_in: testv4, aclv6_in: testv6, aclmac_in: testmac, state: 'present' }

     - name: Layer3 Interface configuration
       arubaoscx_l3_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         ipv4: "{{ item.ipv4 }}"
         ipv6: "{{ item.ipv6 }}"
         qos_rate: "{{ item.qos_rate }}"
         qos_schedule_profile: "{{ item.qos_schedule_profile }}"
         aclv4_in: "{{ item.aclv4_in }}"
         aclv6_in: "{{ item.aclv6_in }}"
         aclmac_in: "{{ item.aclmac_in }}"
         aclv4_out: "{{ item.aclv4_out }}"
         vrf: "{{ item.vrf }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: 1/1/4, admin_state: up, description: test, ipv4: ['10.10.10.2/24', '1.2.3.4/24'], ipv6: ['2001:db8::1234/32', '2000:db8::1234/32'], qos_rate: {'unknown-unicast': 100pps,'broadcast': 200pps, 'multicast': 300pps}, qos_schedule_profile: dwrr, aclv4_in: testv4, aclv6_in: testv6, aclmac_in: testmac, aclv4_out: testegress, vrf: myvrf, state: present }

     - name: VLAN Interface configuration
       arubaoscx_vlan_interface:
         interface: "{{ item.interface }}"
         admin_state: "{{ item.admin_state }}"
         description: "{{ item.description }}"
         ipv4: "{{ item.ipv4 }}"
         ipv6: "{{ item.ipv6 }}"
         vrf: "{{ item.vrf }}"
         state: "{{ item.state }}"
       with_items:
         - { interface: vlan2, admin_state: up, description: InterfaceVLAN2, ipv4: ['1.3.4.5/24', '1.2.3.4/24'], ipv6: ['2001:db8::1234/32', '2000:db8::1234/32'], vrf: myvrf, state: present }
