- name: Create and configure a ports on the controller
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Add ports
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: int_gig
        data: [{"slot/module/port": "0/0/1"}, {"slot/module/port": "0/0/2"}]
        verify_cert: True
