- name: Add a vlan or multiple vlans
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Add two vlans and a vlan range
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: vlan_id
        data: { "id": 47 }
        verify_cert: True
