- name: Whitelist APs
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Add AP whitelist to the controller
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: wdb_cpsec_add_mac
        data: { "ap_name": "test_ap", "ap_group": "default", "name": "<ap-mac>" }
        verify_cert: True
