- name: Create and configure an AP Group
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Create an apgroup
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: ap_group
        data: { "profile-name": "test_apgroup" ,"virtual-ap": [{"profile-name": "test_vap"}] }
        verify_cert: True
