- name: Create and configure an interface vlan
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Assign IP to vlan
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: int_vlan
        data: { "id": <vlan-id> , "int_vlan_ip": {"ipaddr": "<ip-addr>", "ipmask": "<mask>", "ipparams": "ipaddrmask"} }
        verify_cert: True
