- name: Create and configure a port channel
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Create a static port channel
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: int_pc
        data: {"int_pc_trusted": {},"int_pc_port_mode": {"port_mode": "trunk"},"int_pc_trusted_vlan": {"WORD": "1-4094"},"int_pc_vlan_native": {"vlanId": "1"},"int_pc_access_vlan": {"_action": "noop"},"id": "0","int_pc_allowed_vlan": {"WORD": "1-4094"},"int_pc_add_gig": [{"slot/module/port": "0/0/5"}, {"slot/module/port": "0/0/4"}]}
        verify_cert: True
