- name: Create an Authentication Server
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Add a radius server
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: rad_server
        data: { "rad_server_name": "test_radius_server" ,"rad_host": {"host": "<radius-server-ip>"}, "rad_key":{"key": "<change-me>"} }
        verify_cert: True
