- name: Create and configure a SSID Profile
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Create a ssid profile with essid and opmode
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: ssid_prof
        data: { "profile-name": "test_dot1x", "essid":{"essid":"test_dot1x"}, "opmode":{"wpa2-aes":true} }
        verify_cert: True
