- name: Create and configure a Virtual AP Profile
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Create a vap and add ssid, aaa, vlan to itss
      arubaos_controller_config:
        host: "{{ mm_ip }}"
        username: "{{ mm_username }}"
        password: "{{ mm_password }}"
        method: "{{ method_type }}"
        config_path: "{{ configuration_path }}"
        api_name: virtual_ap
        data: { "profile-name": "test_vap" ,"aaa_profile": {"profile-name": "test_dot1x"}, "ssid_prof": {"profile-name":"test_dot1x"},"vlan":{"vlan":"1"}}
        verify_cert: True
