- name: Set Virtual Controller IP
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Set VC IP
      arubainstant_config:
        host: "{{ virtual_controller_ip }}"
        username: "{{ virtual_controller_username }}"
        password: "{{ virtual_controller_password }}"
        method: POST
        api_type: configuration
        api_name: virtual-controller-ip
        data: { "virtual-controller-ip" : { "vc-ip" : "0.0.0.0" } }
