- name: Create/Update AP syslocation
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: AP syslocation
      arubainstant_config:
        host: "{{ virtual_controller_ip }}"
        username: "{{ virtual_controller_username }}"
        password: "{{ virtual_controller_password }}"
        method: POST
        api_type: configuration
        api_name: syslocation
        data: { "syslocation_info" : { "action" : "create", "syslocation" : "Location1"} }
