- name: Add Zone
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Configure zone on an Instant AP
      arubainstant_config:
        host: "{{ virtual_controller_ip }}"
        username: "{{ virtual_controller_username }}"
        password: "{{ virtual_controller_password }}"
        method: POST
        api_type: action
        api_name: zone
        data: { "iap_ip_addr" : "1.1.1.1", "zone_info" : { "action" : "create", "zonename" : "my-zone-name" } }
